gui:
  language: 'en'
  expandFocusedSidePanel: true
  timeFormat: "2006-01-02 15:04"
  shortTimeFormat: '15:04'
  nerdFontsVersion: '3'
  # https://github.com/catppuccin/lazygit/blob/main/themes/macchiato/blue.yml
  theme:
    activeBorderColor:
      - '#8aadf4'
      - bold
    inactiveBorderColor:
      - '#a5adcb'
    optionsTextColor:
      - '#8aadf4'
    selectedLineBgColor:
      - '#363a4f'
    cherryPickedCommitBgColor:
      - '#494d64'
    cherryPickedCommitFgColor:
      - '#8aadf4'
    unstagedChangesColor:
      - '#ed8796'
    defaultFgColor:
      - '#cad3f5'
    searchingActiveBorderColor:
      - '#eed49f'

  authorColors:
    '*': '#b7bdf8'
keybinding:
  universal:
    prevItem: 'k' # go one line up
    nextItem: 'j' # go one line down
    prevItem-alt: '<disabled>' # go one line up
    nextItem-alt: '<disabled>' # go one line down
    prevPage: '<c-u>' # go to next page in list
    nextPage: '<c-d>' # go to previous page in list
    gotoTop: 'g' # go to top of list
    gotoBottom: 'G' # go to bottom of list
    prevBlock: '<c-k>' # goto the previous block / panel
    nextBlock: '<c-j>' # goto the next block / panel
    prevBlock-alt: '<disabled>' # goto the previous block / panel
    nextBlock-alt: '<disabled>' # goto the next block / panel
    select: '<enter>'
    goInto: 'l'
    openRecentRepos: '<c-o>'
    scrollUpMain: '<c-b>' # main panel scroll up
    scrollDownMain: '<c-f>' # main panel scroll down
    scrollUpMain-alt1: '<disabled>' # main panel scroll up
    scrollDownMain-alt1: '<disabled>' # main panel scroll down
    scrollUpMain-alt2: '<disabled>' # main panel scroll up
    scrollDownMain-alt2: '<disabled>' # main panel scroll down
    nextTab: '.'
    prevTab: ','
    nextScreenMode: '='
    prevScreenMode: '-'
    copyToClipboard: 'y'
    rangeSelectUp: 'K'
    rangeSelectDown: 'J'
  files:
    findBaseCommitForFixup: 'F'
    openStatusFilter: 't'
    copyFileInfoToClipboard: 'Y'
  commits:
    viewResetOptions: '<backspace>'
    moveDownCommit: '>' # move commit down one
    moveUpCommit: '<' # move commit up one
    checkoutCommit: '<enter>'
    resetCherryPick: '<c-r>'
    copyCommitAttributeToClipboard: 'Y'
  stash:
    popStash: '<backspace>'
git:
  pagers:
    - externalDiffCommand: '$LOCALAPPDATA/lazygit/delta-diff.bat'
