#################
# Track Selection #
###################

slang=chi,chs,sc,zh



####################
# Playback Control #
####################

# pause=yes
hr-seek-framedrop=no
loop-playlist=inf
# loop-file=inf



####################
# Program Behavior #
####################

vo=gpu
# log-file="~~/log"
# save-position-on-quit=yes
# watch-later-directory="~~/watch_later"
idle=yes
# watch-later-options=vid,aid,sid



#########
# Video #
#########

hwdec=nvdec-copy
hwdec-codecs=all



#########
# Audio #
#########

ao=wasapi
volume-max=200
audio-file-auto=fuzzy



#############
# Subtitles #
#############

# sub-ass-force-margins=yes
sub-ass-vsfilter-blur-compat=no
sub-auto=fuzzy
sub-font-size=32
# sub-back-color="#641C1C1C"



##########
# Window #
##########

title=${media-title} [${time-pos}/${duration}]
keep-open=yes
no-border
# geometry=50%x50%
autofit-larger=80%x80%
autofit-smaller=50%x50%
cursor-autohide=1000
hidpi-window-scale=no



#########
# Input #
#########

input-builtin-bindings=no



#######
# OSD #
#######

osc=no
osd-bar=no
osd-on-seek=msg
osd-duration=2000
osd-font-size=32
osd-playing-msg="${filename}"
# osd-bar-align-y=-1
# osd-bar-w=100
# osd-bar-h=2
osd-border-size=1
osd-fractions=yes



##############
# Screenshot #
##############

screenshot-format=png
screenshot-tag-colorspace=yes
screenshot-template="%F-%p"
screenshot-directory="~~/screenshots"
screenshot-jpeg-quality=100
screenshot-jpeg-source-chroma=no
screenshot-png-compression=5
screenshot-webp-lossless=yes
screenshot-webp-quality=100



###################
# Software Scaler #
###################

sws-allow-zimg=no



########################
# GPU renderer options #
########################

scale=ewa_lanczossharp
cscale=ewa_lanczossharp
dscale=mitchell
tscale=oversample
# correct-downscaling=yes
# linear-downscaling=yes
# linear-upscaling=yes
# sigmoid-upscaling=yes
interpolation=yes
dither-depth=auto
# deband=yes
gpu-context=d3d11
# icc-profile-auto=yes
# icc-cache-dir="~~/cache/icc"
blend-subtitles=video
# gpu-shader-cache-dir="~~/cache/shader"



#################
# Miscellaneous #
#################

# video-sync=display-resample
video-sync-max-video-change=5



#################
# VIDEO FILTERS #
#################

# vf-append=format=gamma=gamma2.2


