###################
# Track Selection #
###################

alang=chs,sc,zh,chi,zho
slang=chs,sc,zh,chi,zho



####################
# Playback Control #
####################

pause=no
hr-seek-framedrop=no
loop-playlist=inf
loop-file=no



####################
# Program Behavior #
####################

# log-file="~~/log"
idle=yes
load-scripts=yes
use-filedir-conf=yes
ytdl=yes
# ytdl-raw-options-append=cookies=[D:/cookies.txt]
load-stats-overlay=yes
load-osd-console=yes
load-auto-profiles=auto



###############
# Watch Later #
###############

# save-position-on-quit=yes
# watch-later-directory="~~/cache/watch_later"
# watch-later-options=vid,aid,sid



#########
# Video #
#########

vo=gpu
hwdec=nvdec-copy
panscan=0.0
hwdec-codecs=all
vd-lavc-dr=yes



#########
# Audio #
#########

audio-pitch-correction=yes
audio-exclusive=no
ao=wasapi
volume=100
audio-channels=stereo
volume-max=200
audio-file-auto=fuzzy



#############
# Subtitles #
#############

sub-ass-scale-with-window=no
embeddedfonts=yes
sub-ass-override=yes
sub-ass-force-margins=no
sub-use-margins=yes
sub-ass-vsfilter-aspect-compat=yes
sub-ass-vsfilter-blur-compat=yes
sub-ass-vsfilter-color-compat=basic
stretch-image-subs-to-screen=no
image-subs-video-resolution=no
sub-auto=fuzzy
sub-file-paths=sub;subtitles;字幕;C:/字幕库
# sub-font="LXGW WenKai"
sub-font-size=32
sub-back-color="#641C1C1C"



##########
# Window #
##########

title=${media-title} [${time-pos}/${duration}]
fullscreen=no
keep-open=yes
ontop=no
border=no
# geometry=50%x50%
autofit-larger=80%x80%
autofit-smaller=40%x40%
cursor-autohide=1000
keepaspect-window=no
hidpi-window-scale=no



###########
# Demuxer #
###########

demuxer-max-bytes=4MiB



#########
# Input #
#########

input-builtin-bindings=no



#######
# OSD #
#######

osc=no
osd-bar=no
osd-on-seek=msg
osd-duration=2000
osd-font-size=40
osd-playing-msg="${playlist-pos-1}. ${filename}"
osd-playing-msg-duration=4000
osd-bar-align-y=-1
osd-bar-w=100
osd-bar-h=1
osd-blur=0
# osd-border-color="#B3008B8B"
osd-border-size=3
# osd-color="#B300FFFF"
osd-fractions=yes



##############
# Screenshot #
##############

screenshot-format=png
screenshot-tag-colorspace=yes
screenshot-high-bit-depth=no
screenshot-template="%F-%p"
screenshot-directory="~~/screenshots"
screenshot-jpeg-quality=100
screenshot-jpeg-source-chroma=yes
screenshot-png-compression=5
screenshot-png-filter=0
screenshot-webp-lossless=yes
screenshot-webp-quality=100
screenshot-webp-compression=3
screenshot-jxl-distance=0
screenshot-jxl-effort=5



########################
# GPU renderer options #
########################

scale=ewa_lanczossharp
cscale=ewa_lanczossharp
dscale=mitchell
tscale=oversample
scaler-resizes-only=no
correct-downscaling=yes
sigmoid-upscaling=yes
interpolation=yes
dither-depth=no
dither=fruit
d3d11-exclusive-fs=no
d3d11-flip=yes
deband=no
gpu-context=d3d11
target-prim=auto
# icc-profile-auto=yes
# icc-cache-dir="~~/cache/icc"
blend-subtitles=no
background="#778899"
# gpu-shader-cache-dir="~~/cache/shader"



#################
# Miscellaneous #
#################

# video-sync=display-resample
video-sync-max-video-change=5


