###################
# Track Selection #
###################

alang=chs,sc,zh,chi,zho
slang=chs,sc,zh,chi,zho

####################
# Playback Control #
####################

# pause=yes
hr-seek-framedrop=no
loop-playlist=inf
loop-file=no

####################
# Program Behavior #
####################

# log-file="~~/log"
idle=yes
# load-scripts=no
use-filedir-conf=yes
# ytdl-raw-options-append=cookies-from-browser=edge

###############
# Watch Later #
###############

# save-position-on-quit=yes
# watch-later-directory="~~/cache/watch_later"
# watch-later-options=start,vid,aid,sid

#########
# Video #
#########

# vo=gpu-next
hwdec=auto-copy
hwdec-codecs=all

#########
# Audio #
#########

# audio-device="wasapi/{xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx}"
# audio-exclusive=yes
ao=wasapi
volume=100
audio-channels=stereo
volume-max=200
audio-file-auto=fuzzy

#############
# Subtitles #
#############

# sub-scale-with-window=no
# sub-ass-scale-with-window=yes
# sub-ass-force-style=Fontname=LXGW WenKai Mono
# sub-ass-override=force
sub-ass-force-margins=yes
sub-use-margins=yes
sub-ass-vsfilter-blur-compat=no
# stretch-image-subs-to-screen=yes
# image-subs-video-resolution=yes
sub-auto=fuzzy
sub-file-paths=sub
subtitles
# sub-font="LXGW WenKai Mono"
sub-font-size=44
# sub-back-color="#641C1C1C"
sub-blur=1
sub-border-size=4
# sub-color="#FFD766"
# sub-shadow-offset=2

##########
# Window #
##########

title=${media-title} [${time-pos}/${duration}]
keep-open=yes
# ontop=yes
border=no
# geometry=50%x50%
autofit-larger=80%x80%
autofit-smaller=40%x40%
cursor-autohide=1000
# auto-window-resize=no
keepaspect-window=no
hidpi-window-scale=no

###########
# Demuxer #
###########

demuxer-max-bytes=4MiB

#########
# Input #
#########

input-builtin-bindings=no
# input-ipc-server=mpvpipe

#######
# OSD #
#######

osc=no
osd-bar=no
osd-on-seek=msg
osd-duration=2000
osd-font-size=40
# osd-playing-msg="${playlist-pos-1}. ${filename}"
# osd-playing-msg-duration=3000
osd-bar-align-y=-1
osd-bar-w=100
osd-bar-h=1.5
# osd-blur=1
# osd-border-color="#FFFFFF"
osd-border-size=1
# osd-color="#672168"
osd-fractions=yes

##############
# Screenshot #
##############

screenshot-format=png
screenshot-tag-colorspace=no
screenshot-high-bit-depth=no
screenshot-template="%F-%p"
screenshot-directory="~~/screenshots"
screenshot-jpeg-quality=100
# screenshot-jpeg-source-chroma=no
screenshot-webp-lossless=yes
screenshot-webp-compression=0
screenshot-jxl-distance=0

########################
# GPU renderer options #
########################

scale=ewa_lanczossharp
cscale=ewa_lanczossharp
dscale=mitchell
tscale=oversample
# correct-downscaling=yes
# sigmoid-upscaling=yes
interpolation=yes
# dither-depth=10
# dither=error-diffusion
# d3d11-exclusive-fs=yes
# d3d11-flip=no
# d3d11-adapter="NVIDIA GeForce RTX 2070 Super"
# glsl-shaders-append="~~/shaders/AMD-FSR-EASU_rgb.glsl"
# deband=yes
# gpu-context=winvk
# tone-mapping=bt.2390
tone-mapping-mode=hybrid
gamut-mapping-mode=clip
# target-prim=display-p3
# target-trc=gamma2.2
# icc-profile-auto=yes
# icc-cache=yes
# icc-cache-dir="~~/cache/icc"
# blend-subtitles=video
background="#778899"
# gpu-shader-cache=yes
# gpu-shader-cache-dir="~~/cache/shader"

#################
# Miscellaneous #
#################

# video-sync=display-resample
video-sync-max-video-change=5
