# Configure the format of the prompt
format = '$os $all$fill$battery$time$line_break$character'

# Right prompt which renders on the same line as the input
right_format = ''

# Timeout for starship to scan files (in milliseconds)
scan_timeout = 30

# Timeout for commands executed by starship (in milliseconds)
command_timeout = 1000

# Inserts blank line between shell prompts
add_newline = false

# Sets which color palette from palettes to use.
# palette = ''

# Collection of color palettes that assign colors to user-defined names. Note that color palettes cannot reference their own color definitions
# palettes = {}



[battery]
full_symbol = ' '
charging_symbol = ' '
discharging_symbol = '  '
unknown_symbol = ' '
empty_symbol = ' '

[[battery.display]]
threshold = 10
style = 'bold #fb4934'
discharging_symbol = ' '

[[battery.display]]
threshold = 30
style = 'bold #fe8019'
discharging_symbol = ' '

[[battery.display]]
threshold = 70
style = 'bold #fabd2f'
discharging_symbol = ' '

[[battery.display]]
threshold = 90
style = 'bold #b8bb26'
discharging_symbol = ' '

[[battery.display]]
threshold = 100
style = 'bold #8ec07c'
discharging_symbol = ' '



[character]
success_symbol = '[>>](bold green)'
error_symbol = '[xx](bold red)'
vimcmd_symbol = '[<<](bold green)'
vimcmd_replace_one_symbol = '[<<](bold purple)'
vimcmd_replace_symbol = '[<<](bold purple)'
vimcmd_visual_symbol = '[<<](bold yellow)'



[conda]
symbol = ' '



[directory]
truncation_length = 0
read_only = ' 󰌾'
use_os_path_sep = false



[fill]
symbol = ' '



[os]
style = 'blue'
disabled = false

[os.symbols]
Arch = " "
Windows = " "



[time]
style = 'bold #d6acff'
disabled = false



[username]
disabled = true
