patch:
  app_options:
    code.exe:
      ascii_mode: true
    devecostudio64.exe:
      ascii_mode: true
    wezterm-gui.exe:
      ascii_mode: true
    windowsterminal.exe:
      ascii_mode: true

  style:
    color_scheme: win11dark
    font_face: Sarasa Mono SC
    label_font_face: Sarasa Mono SC
    comment_font_face: Sarasa Mono SC
    font_point: 20
    label_font_point: 20
    comment_font_point: 20
    horizontal: true
    inline_preedit: true
    layout:
      border_width: 2
      margin_x: 0
      margin_y: 0
      spacing: 20
      candidate_spacing: 20
      hilite_padding: 4
      round_corner: 8
      corner_radius: 8

  preset_color_schemes/win11dark:
    name: "Win11暗色 / Win11Dark"
    border_color:                   0x0c202020
    back_color:                     0x303030
    hilited_back_color:             0x20202020
    hilited_candidate_back_color:   0x7fd07c3a
    hilited_candidate_border_color: 0xd07c3a
    candidate_back_color:           0x07d07c3a
    hilited_text_color:             0xf9f9f9
    hilited_label_color:            0xf9f9f9
    hilited_candidate_text_color:   0xf9f9f9
    hilited_comment_text_color:     0xf9f9f9
    # hilited_mark_color:             0x212fe6
    text_color:                     0xc9c9c9
    label_color:                    0xc9c9c9
    candidate_text_color:           0xc9c9c9
    comment_text_color:             0xc9c9c9
    shadow_color:                   0x60000000
