[mgr]

prepend_keymap = [
    { on = "<C-w>",            run = "plugin close-and-restore-tab close_to_left",                   desc = "Close the current tab and turn to left tab, or quit if it is last tab" },
    { on = "<C-t>",            run = "plugin close-and-restore-tab restore",                         desc = "Restore the closed tab" },

    # Navigation
    { on = "l",                run = "plugin smart-enter",                                           desc = "Enter the child directory, or open the file" },

    # Seeking
    { on = "<C-b>",            run = "seek -5",                                                      desc = "Seek up 5 units in the preview" },
    { on = "<C-f>",            run = "seek 5",                                                       desc = "Seek down 5 units in the preview" },

    # Selection
    { on = "J",                run = [ "toggle", "arrow next" ],                                     desc = "Toggle the current selection state and down" },
    { on = "K",                run = [ "toggle", "arrow prev" ],                                     desc = "Toggle the current selection state and up" },

    # Operation
    { on = "o",                run = "plugin smart-open",                                            desc = "Open the directory in explorer, or open the file" },
    { on = "O",                run = "plugin smart-open cwd",                                        desc = "Open the current directory in explorer" },
    { on = "<Enter>",          run = "open --interactive",                                           desc = "Open selected files interactively" },
    { on = "c",                run = "yank",                                                         desc = "Yank selected files (copy)" },
    { on = "C",                run = "unyank",                                                       desc = "Cancel the yank status" },
    { on = "d",                run = "remove --force",                                               desc = "Trash selected files" },
    { on = "A",                run = "create --dir",                                                 desc = "Create a directory" },
    { on = [ ";", ";" ],       run = "shell --interactive",                                          desc = "Run a shell command" },
    { on = [ ";", ":" ],       run = "shell --block --interactive",                                  desc = "Run a shell command (block until finishes)" },
    { on = [ ";", "l" ],       run = "shell --block lazygit",                                        desc = "Open lazygit" },
    { on = [ "T", "." ],       run = "hidden toggle",                                                desc = "Toggle the visibility of hidden files" },
    { on = [ "s", "f" ],       run = "search --via=fd '--hidden --no-ignore'",                       desc = "Search files by name via fd" },
    { on = [ "s", "r" ],       run = "search --via=rg '--hidden --no-ignore'",                       desc = "Search files by content via ripgrep" },
    { on = [ "s", "n" ],       run = "escape --search",                                              desc = "Cancel the ongoing search" },
    { on = "<C-p>",            run = "plugin fzf",                                                   desc = "Jump to a file/directory via fzf" },
    { on = [ "<Space>", "/" ], run = "plugin fzf-rg",                                                desc = "Reveal a file using fzf by content" },

    # Linemode
    { on = [ "T", "m", "s" ],  run = "linemode size",                                                desc = "Linemode: size" },
    { on = [ "T", "m", "p" ],  run = "linemode permissions",                                         desc = "Linemode: permissions" },
    { on = [ "T", "m", "b" ],  run = "linemode btime",                                               desc = "Linemode: btime" },
    { on = [ "T", "m", "m" ],  run = "linemode mtime",                                               desc = "Linemode: mtime" },
    { on = [ "T", "m", "o" ],  run = "linemode owner",                                               desc = "Linemode: owner" },
    { on = [ "T", "m", "n" ],  run = "linemode none",                                                desc = "Linemode: none" },

    # Copy
    { on = [ "y", "y" ],       run = "copy path",                                                    desc = "Copy the file path" },
    { on = [ "y", "d" ],       run = "copy dirname",                                                 desc = "Copy the directory path" },
    { on = [ "y", "f" ],       run = "copy filename",                                                desc = "Copy the filename" },
    { on = [ "y", "w" ],       run = "copy name_without_ext",                                        desc = "Copy the filename without extension" },

    # Sorting
    { on = [ "T", "s", "m" ],  run = [ "sort mtime --reverse=no", "linemode mtime" ],                desc = "Sort by modified time" },
    { on = [ "T", "s", "M" ],  run = [ "sort mtime --reverse", "linemode mtime" ],                   desc = "Sort by modified time (reverse)" },
    { on = [ "T", "s", "b" ],  run = [ "sort btime --reverse=no", "linemode btime" ],                desc = "Sort by birth time" },
    { on = [ "T", "s", "B" ],  run = [ "sort btime --reverse", "linemode btime" ],                   desc = "Sort by birth time (reverse)" },
    { on = [ "T", "s", "e" ],  run = [ "sort extension --reverse=no", "linemode none" ],             desc = "Sort by extension" },
    { on = [ "T", "s", "E" ],  run = [ "sort extension --reverse", "linemode none" ],                desc = "Sort by extension (reverse)" },
    { on = [ "T", "s", "a" ],  run = [ "sort alphabetical --reverse=no", "linemode none" ],          desc = "Sort alphabetically" },
    { on = [ "T", "s", "A" ],  run = [ "sort alphabetical --reverse", "linemode none" ],             desc = "Sort alphabetically (reverse)" },
    { on = [ "T", "s", "n" ],  run = [ "sort natural --reverse=no", "linemode none" ],               desc = "Sort naturally" },
    { on = [ "T", "s", "N" ],  run = [ "sort natural --reverse", "linemode none" ],                  desc = "Sort naturally (reverse)" },
    { on = [ "T", "s", "s" ],  run = [ "sort size --reverse=no", "linemode size" ],                  desc = "Sort by size" },
    { on = [ "T", "s", "S" ],  run = [ "sort size --reverse", "linemode size" ],                     desc = "Sort by size (reverse)" },
    { on = [ "T", "s", "r" ],  run = [ "sort random --reverse", "linemode none" ],                   desc = "Sort randomly" },

    { on = [ "T", "S", "m" ],  run = [ "sort mtime --reverse=no", "linemode mtime" ],                desc = "Sort by modified time" },
    { on = [ "T", "S", "M" ],  run = [ "sort mtime --reverse", "linemode mtime" ],                   desc = "Sort by modified time (reverse)" },
    { on = [ "T", "S", "b" ],  run = [ "sort btime --reverse=no", "linemode btime" ],                desc = "Sort by birth time" },
    { on = [ "T", "S", "B" ],  run = [ "sort btime --reverse", "linemode btime" ],                   desc = "Sort by birth time (reverse)" },
    { on = [ "T", "S", "e" ],  run = [ "sort extension --reverse=no", "linemode none" ],             desc = "Sort by extension" },
    { on = [ "T", "S", "E" ],  run = [ "sort extension --reverse", "linemode none" ],                desc = "Sort by extension (reverse)" },
    { on = [ "T", "S", "a" ],  run = [ "sort alphabetical --reverse=no", "linemode none" ],          desc = "Sort alphabetically" },
    { on = [ "T", "S", "A" ],  run = [ "sort alphabetical --reverse", "linemode none" ],             desc = "Sort alphabetically (reverse)" },
    { on = [ "T", "S", "n" ],  run = [ "sort natural --reverse=no", "linemode none" ],               desc = "Sort naturally" },
    { on = [ "T", "S", "N" ],  run = [ "sort natural --reverse", "linemode none" ],                  desc = "Sort naturally (reverse)" },
    { on = [ "T", "S", "s" ],  run = [ "sort size --reverse=no", "linemode size" ],                  desc = "Sort by size" },
    { on = [ "T", "S", "S" ],  run = [ "sort size --reverse", "linemode size" ],                     desc = "Sort by size (reverse)" },
    { on = [ "T", "S", "r" ],  run = [ "sort random --reverse", "linemode none" ],                   desc = "Sort randomly" },

    # Goto
    { on = [ "g", ";" ],       run = "cd --interactive",                                             desc = "Jump interactively" },
    { on = [ "g", "D", "c" ],  run = "cd C:/",                                                       desc = "Go to C:",            for = "windows" },
    { on = [ "g", "D", "d" ],  run = "cd D:/",                                                       desc = "Go to D:",            for = "windows" },
    { on = [ "g", "a" ],       run = "cd '%APPDATA%'",                                               desc = "Go to $APPDATA",      for = "windows" },
    { on = [ "g", "l" ],       run = "cd '%LOCALAPPDATA%'",                                          desc = "Go to $LOCALAPPDATA", for = "windows" },
    { on = [ "g", "s" ],       run = "cd '~/scoop'",                                                 desc = "Go to Scoop",         for = "windows" },
    { on = [ "g", "S" ],       run = "cd '%APPDATA%/Microsoft/Windows/Start Menu/Programs/Startup'", desc = "Go to Startup",       for = "windows" },

    # Tabs
    { on = "<C-h>",            run = "tab_switch -1 --relative",                                     desc = "Switch to previous tab" },
    { on = "<C-l>",            run = "tab_switch 1 --relative",                                      desc = "Switch to next tab" },

    { on = ",",                run = "tab_swap -1",                                                  desc = "Swap current tab with previous tab" },
    { on = ".",                run = "tab_swap 1",                                                   desc = "Swap current tab with next tab" },

    # Plugin
    { on = "b",                run = "plugin ouch zip",                                              desc = "Compress with ouch" },

    { on = "[",                run = "plugin parent-arrow prev",                                     desc = "Move cursor up" },
    { on = "]",                run = "plugin parent-arrow next",                                     desc = "Move cursor down" },

    { on = "e",                run = "plugin smart-edit",                                            desc = "Edit in the directory, or edit the file" },
    { on = "E",                run = "plugin smart-edit cwd",                                        desc = "Edit in the current directory" },

    { on = [ "z", "s" ],       run = "plugin projects save",                                         desc = "Save current project" },
    { on = [ "z", "l" ],       run = "plugin projects load",                                         desc = "Load project" },
    { on = "Z",                run = "plugin projects load_last",                                    desc = "Load last project" },
    { on = [ "z", "d" ],       run = "plugin projects delete",                                       desc = "Delete project" },
    { on = [ "z", "D" ],       run = "plugin projects delete_all",                                   desc = "Delete all projects" },
    { on = [ "z", "m" ],       run = "plugin projects 'merge current'",                              desc = "Merge current tab to other projects" },
    { on = [ "z", "M" ],       run = "plugin projects 'merge all'",                                  desc = "Merge current project to other projects" },
]

[tasks]

prepend_keymap = [
    { on = "q",                run = "close",                                                        desc = "Close task manager" },
    { on = "l",                run = "inspect",                                                      desc = "Inspect the task" },
    { on = "d",                run = "cancel",                                                       desc = "Cancel the task" },
]

[spot]

prepend_keymap = [
    { on = "c",                run = "copy cell",                                                    desc = "Copy selected cell" },
    { on = "y",                run = "copy cell",                                                    desc = "Copy selected cell" },
]

[pick]

prepend_keymap = [
    { on = "l",                run = "close --submit",                                               desc = "Submit the pick" },
]

[input]

prepend_keymap = [
    { on = "<C-w>",            run = "close",                                                        desc = "Cancel input" },
    { on = "H",                run = "move bol",                                                     desc = "Move to the BOL" },
    { on = "L",                run = "move eol",                                                     desc = "Move to the EOL" },
]

[cmp]

prepend_keymap = [
    { on = "<C-i>",            run = "close --submit",                                               desc = "Submit the completion" },
    { on = "<C-k>",            run = "arrow prev",                                                   desc = "Previous item" },
    { on = "<C-j>",            run = "arrow next",                                                   desc = "Next item" },
]

[help]

prepend_keymap = [
    { on = [ "g", "g" ],       run = "arrow top",                                                    desc = "Move cursor to the top" },
    { on = "G",                run = "arrow bot",                                                    desc = "Move cursor to the bottom" },
]
