[mgr]

sort_by     = "extension"
show_hidden = true

[opener]

edit = [
    { run = 'nvim -p %*',                                           block = true,  desc = "nvim",           for = "windows" },
    { run = 'wezterm start --cwd "%0" -- nvim -p %* -c "cd %:p:h"', orphan = true, desc = "nvim (wezterm)", for = "windows" },
    { run = 'code %*',                                              orphan = true, desc = "code",           for = "windows" },
    { run = 'code -w %*',                                           block = true,  desc = "code (block)",   for = "windows" },
    { run = 'nvim -p "$@"',                                         block = true,  desc = "nvim",           for = "unix" },
    { run = 'code "$@"',                                            orphan = true, desc = "code",           for = "unix" },
    { run = 'code -w "$@"',                                         block = true,  desc = "code (block)",   for = "unix" },
]

ouch = [
    { run = 'ouch d -y %*',                desc = "Extract here with ouch", for = "windows" },
    { run = 'ouch d -y "$@"',              desc = "Extract here with ouch", for = "unix" },
]

[open]

prepend_rules = [
    # Text
    { mime = "application/tex",                                                                             use = [ "edit", "reveal" ] },
    # Archive
    { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", use = [ "ouch", "extract", "reveal" ] },
    { mime = "application/iso9660-image",                                                                   use = [ "extract", "reveal" ] },
    # Exe
    { mime = "application/msdownload",                                                                      use = [ "open", "extract", "reveal" ] },
]

append_rules = [
    # Fallback
    { name = "*",                                                                                           use = [ "open", "edit", "reveal" ] },
]

[plugin]

prepend_fetchers = [
    { id = "git",  name = "*",  run = "git" },
    { id = "git",  name = "*/", run = "git" },
    { id = "mime", name = "*",  run = "mime-ext", prio = "high" },
]

prepend_previewers = [
    # Code
    { mime = "application/{msdownload,tex}",                                                                run = "code" },
    # JSON
    { mime = "application/{json,ndjson}",                                                                   run = "code" },
    # Archive
    { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", run = "ouch" },
]
