[mgr]

sort_by     = "extension"
show_hidden = true

[opener]

7-zip = [
    { run = '7zfm %s',                                                             desc = "打开压缩包 (7-zip)",      for = "windows" },
    { run = '7zg a -ad "%1".7z %s',                                                desc = "添加到压缩包... (7-zip)", for = "windows" },
]

edit = [
    { run = 'nvim -p %s',                                           desc = "nvim",           for = "windows", block = true},
    { run = 'wezterm start --cwd "%h" -- nvim -p %s -c "cd %:p:h"', desc = "nvim (wezterm)", for = "windows", orphan = true },
    { run = 'code %s',                                              desc = "code",           for = "windows", orphan = true},
    { run = 'code -w %s',                                           desc = "code (block)",   for = "windows", block = true },
    { run = 'nvim -p "%s"',                                         desc = "nvim",           for = "unix",    block = true},
    { run = 'code "%s"',                                            desc = "code",           for = "unix",    orphan = true },
    { run = 'code -w "%s"',                                         desc = "code (block)",   for = "unix",    block = true},
]

locale-emulator = [
    { run = 'leproc %s',                                                           desc = "Open (locale-emulator)",  for = "windows" },
]

[open]

prepend_rules = [
    # Text
    { mime = "application/tex",                                                                             use = [ "edit" ] },
    # Archive
    { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", use = [ "extract", "7-zip" ] },
    { mime = "application/iso9660-image",                                                                   use = [ "7-zip" ] },
    # Exe
    { mime = "application/msdownload",                                                                      use = [ "open", "locale-emulator", "7-zip" ] },
]

append_rules = [
    # Folder
    { url = "*/",                                                                                           use = [ "edit", "open", "7-zip", "reveal" ] },
    # Fallback
    { url = "*",                                                                                            use = [ "open", "edit", "7-zip", "reveal" ] },
]

[plugin]

prepend_fetchers = [
    { id = "git",  url = "*",          run = "git" },
    { id = "git",  url = "*/",         run = "git" },
    { id = "mime", url = "local://*",  run = "mime-ext.local",  prio = "high" },
    { id = "mime", url = "remote://*", run = "mime-ext.remote", prio = "high" },
]

prepend_previewers = [
    # Code
    { mime = "application/{msdownload,tex}",                                                                run = "code" },
    # JSON
    { mime = "application/{json,ndjson}",                                                                   run = "code" },
]
