[manager]

ratio       = [ 1, 4, 4 ]
sort_by     = "natural"
show_hidden = true

[opener]

edit = [
    { run = 'nvim "%*"',    block = true,  desc = "nvim",         for = "windows" },
    { run = 'code "%*"',    orphan = true, desc = "code",         for = "windows" },
    { run = 'code -w "%*"', block = true,  desc = "code (block)", for = "windows" },
    { run = 'nvim "$@"',    block = true,  desc = "nvim",         for = "unix" },
    { run = 'code "$@"',    orphan = true, desc = "code",         for = "unix" },
    { run = 'code -w "$@"', block = true,  desc = "code (block)", for = "unix" },
]
extract = [
    { run = 'ouch decompress "%1"', desc = "Extract here", for = "windows" },
    { run = 'ouch decompress "$1"', desc = "Extract here", for = "unix" },
]

[open]

rules = [
    # windows 平台文件优先打开而不是编辑
    { name = "*/",                                             use = [ "open", "edit", "reveal" ]},

    { mime = "text/*",                                         use = [ "edit", "reveal" ] },
    { mime = "image/*",                                        use = [ "open", "reveal" ] },
    { mime = "{audio,video}/*",                                use = [ "play", "reveal" ] },
    { mime = "inode/x-empty",                                  use = [ "edit", "reveal" ] },

    { mime = "application/*zip",                               use = [ "extract", "reveal" ] },
    { mime = "application/x-{tar,bzip*,7z-compressed,xz,rar}", use = [ "extract", "reveal" ] },
    { mime = "application/vnd.rar",                            use = [ "extract", "reveal" ] },

    { mime = "application/json",                               use = [ "edit", "reveal" ] },
    { mime = "*/javascript",                                   use = [ "edit", "reveal" ] },
    { mime = "application/x-tex",                              use = [ "edit", "reveal" ] },

    { mime = "*",                                              use = [ "open", "reveal" ] },
]

[plugin]

preloaders = [
    { name = "*", cond = "!mime",             run = "mime", multi = true, prio = "high" },
    # Image
    { mime = "image/*",                       run = "image" },
    { mime = "image/heic",                    run = "magick" },
    { mime = "image/jxl",                     run = "magick" },
    { mime = "image/*",                       run = "image" },
    # # Video
    # { mime = "video/*",                     run = "video" },
    # # PDF
    # { mime = "application/pdf",             run = "pdf" },
    # # Font
    # { mime = "font/*",                      run = "font" },
    # { mime = "application/vnd.ms-opentype", run = "font" },
]
previewers = [
    { name = "*/",                                             run = "folder", sync = true },
    # Code
    { mime = "text/*",                                         run = "code" },
    { mime = "*/{xml,javascript,x-wine-extension-ini}",        run = "code" },
    { mime = "*/x-tex",                                        run = "code" },
    # JSON
    { mime = "application/json",                               run = "json" },
    # Image
    { mime = "image/svg+xml",                                  run = "magick" },
    { mime = "image/heic",                                     run = "magick" },
    { mime = "image/jxl",                                      run = "magick" },
    { mime = "image/*",                                        run = "image" },
    # # Video
    # { mime = "video/*",                                      run = "video" },
    # # PDF
    # { mime = "application/pdf",                              run = "pdf" },
    # Archive
    { mime = "application/*zip",                               run = "ouch" },
    { mime = "application/x-{tar,bzip*,7z-compressed,xz,rar}", run = "ouch" },
    { mime = "application/vnd.rar",                            run = "ouch" },
    # # Font
    # { mime = "font/*",                                       run = "font" },
    # { mime = "application/vnd.ms-opentype",                  run = "font" },
    # Fallback
    { name = "*",                                              run = "file" },
]
