return {
    dap = {
        Breakpoint          = " ",
        BreakpointCondition = " ",
        BreakpointRejected  = " ",
        LogPoint            = ".>",
        Stopped             = " ",
    },
    diagnostics = {
        Error = " ",
        Hint  = " ",
        Info  = " ",
        Warn  = " ",
    },
    fold = {
        FoldClosed    = "",
        FoldOpened    = "",
        FoldSeparator = " ",
    },
    git = {
        added     = " ",
        conflict  = " ",
        deleted   = " ",
        ignored   = " ",
        modified  = " ",
        renamed   = " ",
        staged    = " ",
        unstaged  = " ",
        untracked = " ",
    },
    kinds = {
        Array         = " ",
        Boolean       = " ",
        Class         = " ",
        Codeium       = "󰘦 ",
        Color         = " ",
        Control       = " ",
        Collapsed     = " ",
        Constant      = " ",
        Constructor   = " ",
        Copilot       = " ",
        Enum          = " ",
        EnumMember    = " ",
        Event         = " ",
        Field         = " ",
        File          = " ",
        Folder        = " ",
        Function      = " ",
        Interface     = " ",
        Key           = " ",
        Keyword       = " ",
        Method        = " ",
        Module        = " ",
        Namespace     = " ",
        Null          = " ",
        Number        = " ",
        Object        = " ",
        Operator      = " ",
        Package       = " ",
        Property      = " ",
        Reference     = " ",
        Snippet       = " ",
        String        = " ",
        Struct        = " ",
        TabNine       = "󰏚 ",
        Text          = " ",
        TypeParameter = " ",
        Unit          = " ",
        Value         = " ",
        Variable      = " ",
    },
}
