frame = "none"
no-multigrid = true

[font]
size = 17.0

[[font.normal]]
family = "Maple Mono NF CN"

[[font.normal]]
family = "Sarasa Mono SC"

[font.features]
"Maple Mono NF CN" = [ "+cv01", "+cv03", "+ss03" ]

[box-drawing]
mode = "font-glyph"
