- name: CopyQ
  identifier:
    kind: Exe
    id: copyq.exe
    matching_strategy: Equals
  float_identifiers:
  - kind: Exe
    id: copyq.exe
    matching_strategy: Equals

- name: Everything
  identifier:
    kind: Class
    id: EVERYTHING
    matching_strategy: Legacy
  options:
  - tray_and_multi_window
- name: Everything1.5a
  identifier:
    kind: Class
    id: EVERYTHING_(1.5a)
    matching_strategy: Legacy
  options:
  - force
  - tray_and_multi_window

- name: Flow Launcher
  identifier:
    kind: Exe
    id: Flow.Launcher.exe
    matching_strategy: Equals
  float_identifiers:
  - kind: Exe
    id: Flow.Launcher.exe
    matching_strategy: Equals
  - kind: Title
    id: Hotkey sink
    matching_strategy: Equals

- name: Microsoft Excel
  identifier:
    kind: Exe
    id: EXCEL.EXE
    matching_strategy: Equals
  options:
  - layered
  float_identifiers:
  - kind: Class
    id: _WwB
    comment: Targets a hidden window spawned by Microsoft Office applications
    matching_strategy: Legacy
- name: Microsoft Word
  identifier:
    kind: Exe
    id: WINWORD.EXE
    matching_strategy: Equals
  options:
  - layered
  float_identifiers:
  - kind: Class
    id: _WwB
    comment: Targets a hidden window spawned by Microsoft Office applications
    matching_strategy: Legacy
- name: Microsoft PowerPoint
  identifier:
    kind: Exe
    id: POWERPNT.EXE
    matching_strategy: Equals
  options:
  - layered
  float_identifiers:
  - kind: Class
    id: _WwB
    comment: Targets a hidden window spawned by Microsoft Office applications
    matching_strategy: Legacy

- name: MyKeymap
  identifier:
    kind: Exe
    id: MyKeymap.exe
    matching_strategy: Equals
  float_identifiers:
  - kind: Exe
    id: MyKeymap.exe
    matching_strategy: Equals

- name: PicView
  identifier:
    kind: Exe
    id: PicView.exe
    matching_strategy: Equals
  options:
  - force

- name: QQ
  identifier:
    kind: Exe
    id: QQ.exe
    matching_strategy: Equals
  options:
  - tray_and_multi_window
  float_identifiers:
  - kind: Title
    id: 图片查看器
    matching_strategy: Legacy
  - kind: Title
    id: 群聊的聊天记录
    matching_strategy: Legacy
  - kind: Title
    id: 语音通话
    matching_strategy: Legacy
  - kind: Title
    id: QQEdit
    matching_strategy: Legacy
- name: WeChat
  identifier:
    kind: Class
    id: WeChatMainWndForPC
    matching_strategy: Equals
  options:
  - force
  - tray_and_multi_window
- name: WeChat
  identifier:
    kind: Class
    id: WeChatLoginWndForPC
    matching_strategy: Equals
  options:
  - force
  - tray_and_multi_window

- name: RemindMe
  identifier:
    kind: Exe
    id: RemindMe.exe
    matching_strategy: Equals
  options:
  - tray_and_multi_window

- name: ShareX
  identifier:
    kind: Exe
    id: ShareX.exe
    matching_strategy: Equals
  options:
  - tray_and_multi_window

- name: Tablacus Explorer
  identifier:
    kind: Class
    id: TablacusExplorer
    matching_strategy: Equals
  options:
  - force

- name: TApplication
  identifier:
    kind: Class
    id: TApplication
    matching_strategy: Equals
  float_identifiers:
  - kind: Class
    id: TApplication
    matching_strategy: Equals

- name: WezTerm
  identifier:
    kind: Exe
    id: wezterm-gui.exe
    matching_strategy: Equals
  options:
  - force

- name: Windows App
  identifier:
    kind: Exe
    id: ApplicationFrameHost.exe
    matching_strategy: Equals
  float_identifiers:
  - kind: Exe
    id: ApplicationFrameHost.exe
    matching_strategy: Equals

- name: Windows Explorer
  identifier:
    kind: Exe
    id: explorer.exe
    matching_strategy: Equals
  float_identifiers:
  - kind: Class
    id: OperationStatusWindow
    comment: Targets copy/move operation windows
    matching_strategy: Legacy

- name: yasb
  identifier:
    kind: Exe
    id: yasb.exe
    matching_strategy: Equals
  float_identifiers:
  - kind: Exe
    id: yasb.exe
    matching_strategy: Equals
