[manager]

sort_by     = "natural"
show_hidden = true

[opener]

edit = [
    { run = 'nvim %*',      block = true,  desc = "nvim",                   for = "windows" },
    { run = 'neovide %*',   orphan = true, desc = "neovide",                for = "windows" },
    { run = 'code %*',      orphan = true, desc = "code",                   for = "windows" },
    { run = 'code -w %*',   block = true,  desc = "code (block)",           for = "windows" },
    { run = 'nvim "$@"',    block = true,  desc = "nvim",                   for = "unix" },
    { run = 'code "$@"',    orphan = true, desc = "code",                   for = "unix" },
    { run = 'code -w "$@"', block = true,  desc = "code (block)",           for = "unix" },
]

ouch = [
    { run = 'ouch d -y %*',                desc = "Extract here with ouch", for = "windows" },
    { run = 'ouch d -y "$@"',              desc = "Extract here with ouch", for = "unix" },
]

[open]

rules = [
    # Folder
    { name = "*/",                                             use = [ "open", "edit", "reveal" ]},
    # Text
    { mime = "text/*",                                         use = [ "edit", "reveal" ] },
    # Image
    { mime = "image/*",                                        use = [ "open", "reveal" ] },
    # Media
    { mime = "{audio,video}/*",                                use = [ "play", "reveal" ] },
    # Archive
    { mime = "application/{,g}zip",                            use = [ "ouch", "extract", "reveal" ] },
    { mime = "application/x-{tar,bzip*,7z-compressed,xz,rar}", use = [ "ouch", "extract", "reveal" ] },
    { mime = "application/x-iso9660-image",                    use = [ "extract", "reveal" ] },
    # JSON
    { mime = "application/{json,x-ndjson}",                    use = [ "edit", "reveal" ] },
    { mime = "*/javascript",                                   use = [ "edit", "reveal" ] },
    # Empty file
    { mime = "inode/x-empty",                                  use = [ "edit", "reveal" ] },
    # Exe
    { mime = "application/vnd.microsoft.portable-executable",  use = [ "open", "extract", "reveal" ] },
    # Fallback
    { mime = "*",                                              use = [ "open", "reveal" ] },
]

[plugin]

preloaders = [
    # Image
    # { mime = "image/{avif,hei?,jxl,svg+xml}",                run = "magick" },
    { mime = "image/*",                                        run = "image" },
    # # Video
    # { mime = "video/*",                                      run = "video" },
    # # PDF
    # { mime = "application/pdf",                              run = "pdf" },
    # # Font
    # { mime = "font/*",                                       run = "font" },
    # { mime = "application/vnd.ms-opentype",                  run = "font" },
]

previewers = [
    { name = "*/",                                             run = "folder", sync = true },
    # Code
    { mime = "text/*",                                         run = "bat" },
    { mime = "*/{xml,javascript,x-wine-extension-ini}",        run = "bat" },
    # JSON
    { mime = "application/{json,x-ndjson}",                    run = "bat" },
    # Image
    # { mime = "image/{avif,hei?,jxl,svg+xml}",                run = "magick" },
    { mime = "image/*",                                        run = "image" },
    # # Video
    # { mime = "video/*",                                      run = "video" },
    # # PDF
    # { mime = "application/pdf",                              run = "pdf" },
    # Archive
    { mime = "application/{,g}zip",                            run = "ouch" },
    { mime = "application/x-{tar,bzip*,7z-compressed,xz,rar}", run = "ouch" },
    { mime = "application/x-iso9660-image",                    run = "archive" },
    # # Font
    # { mime = "font/*",                                       run = "font" },
    # { mime = "application/vnd.ms-opentype",                  run = "font" },
    # Empty file
    { mime = "inode/x-empty",                                  run = "empty" },
    # Fallback
    { name = "*",                                              run = "file" },
]
