# : Manager {{{

[mgr]
cwd = { fg = "#56b6c2" }

# Hovered
hovered         = { fg = "#282c34", bg = "#61afef" }
preview_hovered = { underline = true }

# Find
find_keyword  = { fg = "#e5c07b", bold = true, italic = true, underline = true }
find_position = { fg = "#c678dd", bg = "reset", bold = true, italic = true }

# Symlink
symlink_target = { italic = true }

# Marker
marker_copied   = { fg = "#98c379", bg = "#98c379" }
marker_cut      = { fg = "#e06c75", bg = "#e06c75" }
marker_marked   = { fg = "#56b6c2", bg = "#56b6c2" }
marker_selected = { fg = "#61afef", bg = "#61afef" }

# Count
count_copied   = { fg = "#282c34", bg = "#98c379" }
count_cut      = { fg = "#282c34", bg = "#e06c75" }
count_selected = { fg = "#282c34", bg = "#61afef" }

# Border
border_symbol = "│"
border_style  = { fg = "#abb2bf" }

# Highlighting
syntect_theme = ""

# : }}}


# : Tabs {{{

[tabs]
active   = { fg = "#282c34", bg = "#61afef" }
inactive = { fg = "#abb2bf", bg = "#5c6370" }

# Separator
sep_inner = { open = "", close = "" }
sep_outer = { open = "", close = "" }

# : }}}


# : Mode {{{

[mode]

normal_main = { fg = "#282c34", bg = "#61afef", bold = true }
normal_alt  = { fg = "#61afef", bg = "#5c6370" }

# Select mode
select_main = { fg = "#282c34", bg = "#e06c75", bold = true }
select_alt  = { fg = "#e06c75", bg = "#5c6370" }

# Unset mode
unset_main = { fg = "#282c34", bg = "#e06c75", bold = true }
unset_alt  = { fg = "#e06c75", bg = "#5c6370" }

# : }}}


# : Status bar {{{

[status]
overall   = {}
sep_left  = { open = "", close = "" }
sep_right = { open = "", close = "" }

# Permissions
perm_sep = { fg = "#abb2bf" }
perm_type = { fg = "#61afef" }
perm_read = { fg = "#e5c07b" }
perm_write = { fg = "#e06c75" }
perm_exec = { fg = "#98c379" }

# Progress
progress_label  = { bold = true }
progress_normal = { fg = "#61afef", bg = "#5c6370" }
progress_error  = { fg = "#e06c75", bg = "#5c6370" }


# : }}}


# : Which {{{

[which]
cols            = 3
mask            = { bg = "#282c34" }
cand            = { fg = "#56b6c2" }
rest            = { fg = "#abb2bf" }
desc            = { fg = "#c678dd" }
separator       = "   "
separator_style = { fg = "#5c6370" }

# : }}}


# : Confirmation {{{

[confirm]
border     = { fg = "#61afef" }
title      = { fg = "#61afef" }
content    = {}
list       = {}
btn_yes    = { reversed = true }
btn_no     = {}
btn_labels = [ "  [Y]es  ", "  (N)o  " ]

# : }}}


# : Spotter {{{

[spot]
border = { fg = "#61afef" }
title  = { fg = "#61afef" }

# Table
tbl_col  = { fg = "#61afef" }
tbl_cell = { fg = "#e5c07b", reversed = true }

# : }}}


# : Notification {{{

[notify]
title_info  = { fg = "#61afef" }
title_warn  = { fg = "#e5c07b" }
title_error = { fg = "#e06c75" }

# Icons
icon_info  = ""
icon_warn  = ""
icon_error = ""

# : }}}


# : Picker {{{

[pick]
border   = { fg = "#61afef" }
active   = { fg = "#c678dd", bold = true }
inactive = {}

# : }}}


# : Input {{{

[input]
border   = { fg = "#61afef" }
title    = {}
value    = {}
selected = { reversed = true }

# : }}}


# : Completion {{{

[cmp]
border   = { fg = "#61afef" }
active   = { fg = "#282c34", bg = "#61afef" }
inactive = {}

# Icons
icon_file    = ""
icon_folder  = ""
icon_command = ""

# : }}}


# : Task manager {{{

[tasks]
border  = { fg = "#61afef" }
title   = {}
hovered = { fg = "#282c34", bg = "#61afef" }

# : }}}


# : Help menu {{{

[help]
on      = { fg = "#c678dd" }
run     = { fg = "#56b6c2" }
desc    = { fg = "#abb2bf" }
hovered = { bg = "#5c6370", bold = true }
footer  = { fg = "#282c34", bg = "#abb2bf" }

# : }}}


# : File-specific styles {{{

[filetype]

rules = [
    # Images
    { mime = "image/*", fg = "#56b6c2" },

    # Media
    { mime = "{audio,video}/*", fg = "#e5c07b" },

    # Archives
    { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "#c678dd" },

    # Documents
    { mime = "application/{pdf,doc,rtf}", fg = "#d19a66" },

    # Empty files
    # { mime = "inode/empty", fg = "#e06c75" },

    # Special files
    { name = "*", is = "orphan", bg = "#e06c75" },
    { name = "*", is = "exec"  , fg = "#98c379" },

    # Dummy files
    { name = "*", is = "dummy", bg = "#e06c75" },
    { name = "*/", is = "dummy", bg = "#e06c75" },

    # Fallback
    # { name = "*",  fg = "#abb2bf" },
    { name = "*/", fg = "#61afef" },

    { name = "*.exe", fg = "#98c379" },
]

# : }}}
