# : Manager {{{

[manager]
cwd = { fg = "#56b6c2" }

# Hovered
hovered         = { fg = "#282c34", bg = "#61afef" }
preview_hovered = { underline = true }

# Find
find_keyword  = { fg = "#e2be7d", bold = true, italic = true, underline = true }
find_position = { fg = "#c678dd", bg = "reset", bold = true, italic = true }

# Marker
marker_copied   = { fg = "#98c379", bg = "#98c379" }
marker_cut      = { fg = "#e06c75", bg = "#e06c75" }
marker_marked   = { fg = "#56b6c2",   bg = "#56b6c2" }
marker_selected = { fg = "#61afef", bg = "#61afef" }

# Tab
tab_active   = { fg = "#282c34", bg = "#61afef" }
tab_inactive = { fg = "#abb2bf", bg = "#5c6370" }
tab_width    = 30

# Count
count_copied   = { fg = "#282c34", bg = "#98c379" }
count_cut      = { fg = "#282c34", bg = "#e06c75" }
count_selected = { fg = "#282c34", bg = "#61afef" }

# Border
border_symbol = "│"
border_style  = { fg = "#abb2bf" }

# Highlighting
syntect_theme = ""

# : }}}


# : Status {{{

[status]
separator_open  = ""
separator_close = ""
separator_style = { fg = "#5c6370", bg = "#5c6370" }

# Mode
mode_normal = { fg = "#282c34", bg = "#61afef", bold = true }
mode_select = { fg = "#282c34", bg = "#98c379", bold = true }
mode_unset  = { fg = "#282c34", bg = "#e06c75", bold = true }

# Progress
progress_label  = { bold = true }
progress_normal = { fg = "#61afef", bg = "#5c6370" }
progress_error  = { fg = "#e06c75", bg = "#5c6370" }

# Permissions
permissions_t = { fg = "#61afef" }
permissions_r = { fg = "#e5c07b" }
permissions_w = { fg = "#e06c75" }
permissions_x = { fg = "#98c379" }
permissions_s = { fg = "#abb2bf" }

# : }}}


# : Select {{{

[select]
border   = { fg = "#61afef" }
active   = { fg = "#c678dd", bold = true }
inactive = {}

# : }}}


# : Input {{{

[input]
border   = { fg = "#61afef" }
title    = {}
value    = {}
selected = { reversed = true }

# : }}}


# : Completion {{{

[completion]
border   = { fg = "#61afef" }
active   = { fg = "#282c34", bg = "#61afef" }
inactive = {}

# Icons
icon_file    = ""
icon_folder  = ""
icon_command = ""

# : }}}


# : Tasks {{{

[tasks]
border  = { fg = "#61afef" }
title   = {}
hovered = { fg = "#282c34", bg = "#61afef" }

# : }}}


# : Which {{{

[which]
cols            = 3
mask            = { bg = "#282c34" }
cand            = { fg = "#56b6c2" }
rest            = { fg = "#abb2bf" }
desc            = { fg = "#c678dd" }
separator       = "   "
separator_style = { fg = "#5c6370" }

# : }}}


# : Help {{{

[help]
on      = { fg = "#c678dd" }
run     = { fg = "#56b6c2" }
desc    = { fg = "#abb2bf" }
hovered = { bg = "#5c6370", bold = true }
footer  = { fg = "#282c34", bg = "#abb2bf" }

# : }}}


# : Notify {{{

[notify]
title_info  = { fg = "#61afef" }
title_warn  = { fg = "#e5c07b" }
title_error = { fg = "#e06c75" }

# Icons
icon_info  = ""
icon_warn  = ""
icon_error = ""

# : }}}


# : File-specific styles {{{

[filetype]

rules = [
    # Images
    { mime = "image/*", fg = "#56b6c2" },

    # Media
    { mime = "{audio,video}/*", fg = "#e5c07b" },

    # Archives
    { mime = "application/{,g}zip", fg = "#c678dd" },
    { mime = "application/x-{tar,bzip*,7z-compressed,xz,rar}", fg = "#c678dd" },

    # Documents
    { mime = "application/{pdf,doc,rtf,vnd.*}", fg = "#d19a66" },

    # Empty files
    # { mime = "inode/x-empty", fg = "#e06c75" },

    # Special files
    { name = "*", is = "orphan", bg = "#e06c75" },
    { name = "*", is = "exec"  , fg = "#98c379" },

    # Dummy files
    { name = "*", is = "dummy", bg = "#e06c75" },
    { name = "*/", is = "dummy", bg = "#e06c75" },

    # Fallback
    # { name = "*",  fg = "#abb2bf" },
    { name = "*/", fg = "#61afef" }
]
